name: devocional_nuevo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.0.2
  flutter_native_splash: ^2.3.1
  url_launcher: ^6.3.1
  http: ^1.1.0
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  provider: ^6.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8


  flutter_localizations:
    sdk: flutter
  # Push Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.2.0
  # Firebase Cloud Messaging
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  android_alarm_manager_plus: ^4.0.7
  # Para manejar tareas en segundo plano
  workmanager: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.png
    - assets/icons/