name: devocional_nuevo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.3.1
  url_launcher: ^6.2.5
  http: ^1.4.0
  shared_preferences: ^2.2.3
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  auto_size_text: ^3.0.0
  path_provider: ^2.1.3
  provider: ^6.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  material_symbols_icons: ^4.2.0
  flutter_localizations:
    sdk: flutter
  # Push Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  # Firebase Cloud Messaging
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  # Para manejar notificaciones en segundo plano
  android_alarm_manager_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.png
    - assets/icons/