# pubspec.yaml

name: devocional_nuevo
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+47

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_remote_config: ^6.0.1
  package_info_plus: ^8.0.2
  flutter_native_splash: ^2.3.1
  url_launcher: ^6.3.1
  http: ^1.1.0
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  provider: ^6.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  intl: 0.20.2
  cached_network_image: ^3.3.0
  in_app_update: ^4.2.3
  in_app_review: ^2.0.8
  google_fonts: ^6.3.0
  lottie: ^3.3.2
  flutter_localizations:

    sdk: flutter
  # Push Notifications
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  flutter_timezone: ^4.1.1 #para obtener la zona horaria del dispositivo real

  # Firebase dependencies
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # Audio dependencies
  flutter_tts: ^4.1.0
  synchronized: ^3.1.0+1  # For thread safety and mutex protection

  # Google Drive Backup dependencies
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.5
  archive: ^4.0.0
  workmanager: ^0.9.0+3
  
  # Google Play Billing dependencies
  in_app_purchase: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0
  bloc_test: ^10.0.0
  coverage: ^1.7.2
  mockito: ^5.4.4
  build_runner: ^2.4.12

  path_provider_platform_interface: any
  test: ^1.25.7


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.png
    - assets/icons/
    - assets/badges/
    - assets/lottie/tap_screen.json


