# pubspec.yaml

name: devocional_nuevo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.25+25

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: # <-- ÚNICA SECCIÓN DEPENDENCIES
  flutter:
    sdk: flutter

  package_info_plus: ^8.0.2
  flutter_native_splash: ^2.3.1
  url_launcher: ^6.3.1
  http: ^1.1.0
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  provider: ^6.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Firebase Auth
  firebase_auth: ^5.6.2 # AÑADE ESTA LÍNEA (o actualiza a la versión más reciente compatible)

  flutter_localizations:
    sdk: flutter
  # Push Notifications
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  flutter_timezone: ^4.1.1 #para obtener la zona horaria del dispositivo real
  # Firebase Cloud Messaging
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  cloud_firestore: ^5.0.2 # CAMBIO: Added cloud_firestore for database operations

  # Para manejar tareas en segundo plano
  workmanager: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.png
    - assets/icons/