// Mocks generated by Mockito 5.4.4 from annotations
// in integration_test/analytics_integration_test.dart.
// Do not manually edit this file.

import 'package:firebase_analytics/firebase_analytics.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirebaseAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAnalytics extends _i2.Mock implements _i1.FirebaseAnalytics {}
