// Mocks generated by Mockito 5.4.6 from annotations
// in devocional_nuevo/test/helpers/bloc_test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i14;

import 'package:devocional_nuevo/controllers/audio_controller.dart' as _i6;
import 'package:devocional_nuevo/models/devocional_model.dart' as _i11;
import 'package:devocional_nuevo/models/discovery_devotional_model.dart' as _i3;
import 'package:devocional_nuevo/providers/devocional_provider.dart' as _i10;
import 'package:devocional_nuevo/repositories/discovery_repository.dart' as _i7;
import 'package:devocional_nuevo/services/discovery_favorites_service.dart'
    as _i9;
import 'package:devocional_nuevo/services/discovery_progress_tracker.dart'
    as _i4;
import 'package:flutter/material.dart' as _i13;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiscoveryDevotional_1 extends _i1.SmartFake
    implements _i3.DiscoveryDevotional {
  _FakeDiscoveryDevotional_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiscoveryProgress_2 extends _i1.SmartFake
    implements _i4.DiscoveryProgress {
  _FakeDiscoveryProgress_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_3 extends _i1.SmartFake
    implements _i5.SharedPreferences {
  _FakeSharedPreferences_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioController_4 extends _i1.SmartFake
    implements _i6.AudioController {
  _FakeAudioController_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DiscoveryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryRepository extends _i1.Mock
    implements _i7.DiscoveryRepository {
  MockDiscoveryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  _i8.Future<_i3.DiscoveryDevotional> fetchDiscoveryStudy(
    String? id,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDiscoveryStudy,
          [
            id,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<_i3.DiscoveryDevotional>.value(
            _FakeDiscoveryDevotional_1(
          this,
          Invocation.method(
            #fetchDiscoveryStudy,
            [
              id,
              languageCode,
            ],
          ),
        )),
      ) as _i8.Future<_i3.DiscoveryDevotional>);

  @override
  _i8.Future<List<String>> fetchAvailableStudies(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAvailableStudies,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<Map<String, dynamic>> fetchIndex({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchIndex,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [DiscoveryProgressTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryProgressTracker extends _i1.Mock
    implements _i4.DiscoveryProgressTracker {
  MockDiscoveryProgressTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.DiscoveryProgress> getProgress(
    String? studyId, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [
            studyId,
            languageCode,
          ],
        ),
        returnValue:
            _i8.Future<_i4.DiscoveryProgress>.value(_FakeDiscoveryProgress_2(
          this,
          Invocation.method(
            #getProgress,
            [
              studyId,
              languageCode,
            ],
          ),
        )),
      ) as _i8.Future<_i4.DiscoveryProgress>);

  @override
  _i8.Future<void> markSectionCompleted(
    String? studyId,
    int? sectionIndex, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #markSectionCompleted,
          [
            studyId,
            sectionIndex,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> answerQuestion(
    String? studyId,
    int? questionIndex,
    String? answer, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #answerQuestion,
          [
            studyId,
            questionIndex,
            answer,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> completeStudy(
    String? studyId, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeStudy,
          [
            studyId,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resetStudyProgress(
    String? studyId, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetStudyProgress,
          [
            studyId,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<double> getCompletionPercentage(
    String? studyId,
    int? totalSections, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletionPercentage,
          [
            studyId,
            totalSections,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<void> clearAllProgress() => (super.noSuchMethod(
        Invocation.method(
          #clearAllProgress,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [DiscoveryFavoritesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryFavoritesService extends _i1.Mock
    implements _i9.DiscoveryFavoritesService {
  MockDiscoveryFavoritesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.SharedPreferences> get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue:
            _i8.Future<_i5.SharedPreferences>.value(_FakeSharedPreferences_3(
          this,
          Invocation.getter(#prefs),
        )),
      ) as _i8.Future<_i5.SharedPreferences>);

  @override
  _i8.Future<Set<String>> loadFavoriteIds([String? languageCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFavoriteIds,
          [languageCode],
        ),
        returnValue: _i8.Future<Set<String>>.value(<String>{}),
      ) as _i8.Future<Set<String>>);

  @override
  _i8.Future<bool> toggleFavorite(
    String? studyId, [
    String? languageCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [
            studyId,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [DevocionalProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDevocionalProvider extends _i1.Mock
    implements _i10.DevocionalProvider {
  MockDevocionalProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.Devocional> get devocionales => (super.noSuchMethod(
        Invocation.getter(#devocionales),
        returnValue: <_i11.Devocional>[],
      ) as List<_i11.Devocional>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isSwitchingVersion => (super.noSuchMethod(
        Invocation.getter(#isSwitchingVersion),
        returnValue: false,
      ) as bool);

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  String get selectedVersion => (super.noSuchMethod(
        Invocation.getter(#selectedVersion),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#selectedVersion),
        ),
      ) as String);

  @override
  List<_i11.Devocional> get favoriteDevocionales => (super.noSuchMethod(
        Invocation.getter(#favoriteDevocionales),
        returnValue: <_i11.Devocional>[],
      ) as List<_i11.Devocional>);

  @override
  bool get showInvitationDialog => (super.noSuchMethod(
        Invocation.getter(#showInvitationDialog),
        returnValue: false,
      ) as bool);

  @override
  bool get isDownloading => (super.noSuchMethod(
        Invocation.getter(#isDownloading),
        returnValue: false,
      ) as bool);

  @override
  bool get isOfflineMode => (super.noSuchMethod(
        Invocation.getter(#isOfflineMode),
        returnValue: false,
      ) as bool);

  @override
  _i6.AudioController get audioController => (super.noSuchMethod(
        Invocation.getter(#audioController),
        returnValue: _FakeAudioController_4(
          this,
          Invocation.getter(#audioController),
        ),
      ) as _i6.AudioController);

  @override
  bool get isAudioPlaying => (super.noSuchMethod(
        Invocation.getter(#isAudioPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isAudioPaused => (super.noSuchMethod(
        Invocation.getter(#isAudioPaused),
        returnValue: false,
      ) as bool);

  @override
  int get currentReadingSeconds => (super.noSuchMethod(
        Invocation.getter(#currentReadingSeconds),
        returnValue: 0,
      ) as int);

  @override
  double get currentScrollPercentage => (super.noSuchMethod(
        Invocation.getter(#currentScrollPercentage),
        returnValue: 0.0,
      ) as double);

  @override
  List<String> get supportedLanguages => (super.noSuchMethod(
        Invocation.getter(#supportedLanguages),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get availableVersions => (super.noSuchMethod(
        Invocation.getter(#availableVersions),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool isDevocionalPlaying(String? devocionalId) => (super.noSuchMethod(
        Invocation.method(
          #isDevocionalPlaying,
          [devocionalId],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String> getVersionsForLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #getVersionsForLanguage,
          [language],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i8.Future<void> initializeData() => (super.noSuchMethod(
        Invocation.method(
          #initializeData,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playDevotional(_i11.Devocional? devocional) =>
      (super.noSuchMethod(
        Invocation.method(
          #playDevotional,
          [devocional],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> pauseAudio() => (super.noSuchMethod(
        Invocation.method(
          #pauseAudio,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resumeAudio() => (super.noSuchMethod(
        Invocation.method(
          #resumeAudio,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleAudioPlayPause(_i11.Devocional? devocional) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleAudioPlayPause,
          [devocional],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getAvailableLanguages() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableLanguages,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> getAvailableVoices() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableVoices,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> getVoicesForLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoicesForLanguage,
          [language],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<void> setTtsLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setTtsLanguage,
          [language],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setTtsVoice(Map<String, String>? voice) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTtsVoice,
          [voice],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setTtsSpeechRate(double? rate) => (super.noSuchMethod(
        Invocation.method(
          #setTtsSpeechRate,
          [rate],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void startDevocionalTracking(
    String? devocionalId, {
    _i13.ScrollController? scrollController,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #startDevocionalTracking,
          [devocionalId],
          {#scrollController: scrollController},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseTracking() => super.noSuchMethod(
        Invocation.method(
          #pauseTracking,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeTracking() => super.noSuchMethod(
        Invocation.method(
          #resumeTracking,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> recordDevocionalRead(String? devocionalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordDevocionalRead,
          [devocionalId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> recordDevocionalHeard(
    String? devocionalId,
    double? listenedPercentage,
    _i13.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordDevocionalHeard,
          [
            devocionalId,
            listenedPercentage,
            context,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #recordDevocionalHeard,
            [
              devocionalId,
              listenedPercentage,
              context,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> setSelectedLanguage(
    String? language,
    _i13.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSelectedLanguage,
          [
            language,
            context,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSelectedVersion(String? version) => (super.noSuchMethod(
        Invocation.method(
          #setSelectedVersion,
          [version],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveFavorites() => (super.noSuchMethod(
        Invocation.method(
          #saveFavorites,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addFavoriteId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #addFavoriteId,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isFavorite(_i11.Devocional? devocional) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [devocional],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<bool> toggleFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  void toggleFavoriteWithContext(
    _i11.Devocional? devocional,
    _i13.BuildContext? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleFavoriteWithContext,
          [
            devocional,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> reloadFavoritesFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #reloadFavoritesFromStorage,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setInvitationDialogVisibility(bool? shouldShow) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInvitationDialogVisibility,
          [shouldShow],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> hasLocalFile(
    int? year,
    String? language, [
    String? version,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasLocalFile,
          [
            year,
            language,
            version,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> downloadAndStoreDevocionales(int? year) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAndStoreDevocionales,
          [year],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> clearOldLocalFiles() => (super.noSuchMethod(
        Invocation.method(
          #clearOldLocalFiles,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isLanguageSupported(String? language) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [language],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<bool> downloadCurrentYearDevocionales() => (super.noSuchMethod(
        Invocation.method(
          #downloadCurrentYearDevocionales,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> downloadDevocionalesForYear(int? year) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDevocionalesForYear,
          [year],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> downloadDevocionalesWithProgress({
    required dynamic Function(double)? onProgress,
    int? startYear = 2025,
    int? endYear = 2026,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDevocionalesWithProgress,
          [],
          {
            #onProgress: onProgress,
            #startYear: startYear,
            #endYear: endYear,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> hasCurrentYearLocalData() => (super.noSuchMethod(
        Invocation.method(
          #hasCurrentYearLocalData,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> hasTargetYearsLocalData() => (super.noSuchMethod(
        Invocation.method(
          #hasTargetYearsLocalData,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> forceRefreshFromAPI() => (super.noSuchMethod(
        Invocation.method(
          #forceRefreshFromAPI,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void clearDownloadStatus() => super.noSuchMethod(
        Invocation.method(
          #clearDownloadStatus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void forceUIUpdate() => super.noSuchMethod(
        Invocation.method(
          #forceUIUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void speakDevocional(String? s) => super.noSuchMethod(
        Invocation.method(
          #speakDevocional,
          [s],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<List<_i11.Devocional>> getDevocionalesNoLeidos() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDevocionalesNoLeidos,
          [],
        ),
        returnValue:
            _i8.Future<List<_i11.Devocional>>.value(<_i11.Devocional>[]),
      ) as _i8.Future<List<_i11.Devocional>>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
