// Mocks generated by Mockito 5.4.6 from annotations
// in devocional_nuevo/test/helpers/iap_mock_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:devocional_nuevo/models/supporter_tier.dart' as _i4;
import 'package:devocional_nuevo/services/iap/i_iap_service.dart' as _i2;
import 'package:in_app_purchase/in_app_purchase.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IIapService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIIapService extends _i1.Mock implements _i2.IIapService {
  MockIIapService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.SupporterTier> get onPurchaseDelivered => (super.noSuchMethod(
        Invocation.getter(#onPurchaseDelivered),
        returnValue: _i3.Stream<_i4.SupporterTier>.empty(),
      ) as _i3.Stream<_i4.SupporterTier>);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  Set<_i4.SupporterTierLevel> get purchasedLevels => (super.noSuchMethod(
        Invocation.getter(#purchasedLevels),
        returnValue: <_i4.SupporterTierLevel>{},
      ) as Set<_i4.SupporterTierLevel>);

  @override
  _i2.IapInitStatus get initStatus => (super.noSuchMethod(
        Invocation.getter(#initStatus),
        returnValue: _i2.IapInitStatus.notStarted,
      ) as _i2.IapInitStatus);

  @override
  bool isPurchased(_i4.SupporterTierLevel? level) => (super.noSuchMethod(
        Invocation.method(
          #isPurchased,
          [level],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.ProductDetails? getProduct(String? productId) =>
      (super.noSuchMethod(Invocation.method(
        #getProduct,
        [productId],
      )) as _i5.ProductDetails?);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.IapResult> purchaseTier(_i4.SupporterTier? tier) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseTier,
          [tier],
        ),
        returnValue: _i3.Future<_i2.IapResult>.value(_i2.IapResult.success),
      ) as _i3.Future<_i2.IapResult>);

  @override
  _i3.Future<void> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
