name: Flutter CI (Chrome)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'

      - name: Show Flutter and Dart version
        run: |
          flutter --version
          dart --version

      - name: Cache Pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (no falla por info/warning)
        run: flutter analyze
        continue-on-error: true

      - name: Run tests
        run: flutter test
        continue-on-error: true

      - name: Run tests in Chrome (Flutter web)
        run: flutter test --platform=chrome --web-renderer html
        continue-on-error: true

      - name: Build APK
        run: flutter build apk --debug
        continue-on-error: true

      - name: Echo basic validation success
        run: echo "Workflow completed. Validación básica lista."
