name: Flutter CI (Ligero y Seguro)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-cache-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # --- PAUSA 1: Limpieza automática ---
      - name: Cleanup (format & safe fixes)
        run: |
          dart format .
          dart fix --apply

      # --- PAUSA 2: Reporte de limpieza ---
      - name: Show code cleanup summary
        run: |
          if git diff --stat | grep -q '[0-9]'; then
            echo "⚠️ Se realizaron limpiezas automáticas en el código:"
            git diff --stat
          else
            echo "✅ No se realizaron limpiezas automáticas."
          fi

      # --- PAUSA 3: Análisis estricto ---
      - name: Analyze code (fail on warnings)
        run: flutter analyze --fatal-infos

      # --- PAUSA 4: Pruebas unitarias ---
      - name: Run unit tests
        run: flutter test
