name: 👋Deploy OpenHands Agent

on:
  workflow_dispatch:
    inputs:
      openhands_version:
        description: 'OpenHands version to deploy'
        required: false
        default: '0.52'
        type: string
      runtime_variant:
        description: 'Runtime variant'
        required: false
        default: 'nikolaik'
        type: string
      log_all_events:
        description: 'Enable logging of all events'
        required: false
        default: true
        type: boolean

env:
  OPENHANDS_VERSION: ${{ github.event.inputs.openhands_version || '0.52' }}
  RUNTIME_VARIANT: ${{ github.event.inputs.runtime_variant || 'nikolaik' }}
  LOG_ALL_EVENTS: ${{ github.event.inputs.log_all_events || 'true' }}

jobs:
  deploy-openhands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Create OpenHands config directory
      run: |
        mkdir -p ~/.openhands
        chmod 755 ~/.openhands

    - name: Pull OpenHands runtime image
      run: |
        echo "Pulling OpenHands runtime image..."
        docker pull docker.all-hands.dev/all-hands-ai/runtime:${{ env.OPENHANDS_VERSION }}-${{ env.RUNTIME_VARIANT }}

    - name: Pull OpenHands main image
      run: |
        echo "Pulling OpenHands main image..."
        docker pull docker.all-hands.dev/all-hands-ai/openhands:${{ env.OPENHANDS_VERSION }}

    - name: Stop any existing OpenHands container
      run: |
        docker stop openhands-app 2>/dev/null || true
        docker rm openhands-app 2>/dev/null || true

    - name: Start OpenHands container
      run: |
        echo "Starting OpenHands container with official command..."
        docker run -d \
          --pull=always \
          -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:${{ env.OPENHANDS_VERSION }}-${{ env.RUNTIME_VARIANT }} \
          -e LOG_ALL_EVENTS=${{ env.LOG_ALL_EVENTS }} \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ~/.openhands:/.openhands \
          -p 3000:3000 \
          --add-host host.docker.internal:host-gateway \
          --name openhands-app \
          docker.all-hands.dev/all-hands-ai/openhands:${{ env.OPENHANDS_VERSION }}

    - name: Wait for OpenHands to be ready
      run: |
        echo "Waiting for OpenHands to start..."
        max_attempts=60
        attempt=0
        
        while [ $attempt -lt $max_attempts ]; do
          if curl -sf http://localhost:3000 >/dev/null 2>&1; then
            echo "✅ OpenHands is ready!"
            break
          fi
          
          echo "⏳ Attempt $((attempt + 1))/$max_attempts: OpenHands not ready yet, waiting 10 seconds..."
          sleep 10
          attempt=$((attempt + 1))
        done
        
        if [ $attempt -eq $max_attempts ]; then
          echo "❌ OpenHands failed to start within the expected time"
          echo "=== Container Logs ==="
          docker logs openhands-app --tail 100
          exit 1
        fi

    - name: Verify OpenHands deployment
      run: |
        echo "=== OpenHands Deployment Verification ==="
        
        echo "📋 Container Status:"
        docker ps -a | grep openhands-app
        
        echo ""
        echo "🔍 Container Details:"
        docker inspect openhands-app --format='{{json .State}}' | jq '.'
        
        echo ""
        echo "📊 Container Stats:"
        docker stats openhands-app --no-stream
        
        echo ""
        echo "📜 Recent Container Logs:"
        docker logs openhands-app --tail 20

    - name: Health Check
      run: |
        echo "=== Health Check ==="
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
        if [ "$response" = "200" ]; then
          echo "✅ OpenHands is responding correctly (HTTP $response)"
        else
          echo "❌ OpenHands returned HTTP status code: $response"
          echo "=== Debugging Information ==="
          docker logs openhands-app --tail 50
          exit 1
        fi

    - name: Display connection information
      run: |
        echo ""
        echo "🎉 OpenHands deployment successful!"
        echo ""
        echo "📋 Deployment Summary:"
        echo "- Version: ${{ env.OPENHANDS_VERSION }}"
        echo "- Runtime: ${{ env.OPENHANDS_VERSION }}-${{ env.RUNTIME_VARIANT }}"
        echo "- Log All Events: ${{ env.LOG_ALL_EVENTS }}"
        echo "- Container Name: openhands-app"
        echo ""
        echo "🌐 Access URLs:"
        echo "- Local: http://localhost:3000"
        echo "- Container IP: $(docker inspect openhands-app --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'):3000"
        echo ""
        echo "🛠️ Management Commands:"
        echo "- View logs: docker logs openhands-app"
        echo "- Stop container: docker stop openhands-app"
        echo "- Remove container: docker rm openhands-app"
        echo ""
        echo "⚠️  Note: You'll need to configure LLM API keys in the UI at http://localhost:3000"

    - name: Keep container running
      run: |
        echo "Container is running and will remain active."
        echo "The workflow completes successfully, but the OpenHands container continues running."
        echo "Remember to manually stop the container when done: docker stop openhands-app"
